Repository lee-ji-hoon/community, pull requests merged in 2022-05, with the labels that each got.

#413 스터디 수정
  src/main/resources/templates/study/study-list.html
Labels: enhancement

#414 공지사항 추가 -> View는 수정 예정
  src/main/java/com/community/domain/inquire/InquireAnswer.java
  src/main/java/com/community/domain/inquire/InquireAnswerRepository.java
  src/main/java/com/community/domain/notice/Notice.java
  src/main/java/com/community/domain/notice/NoticeRepository.java
  src/main/java/com/community/infra/aws/S3.java
  src/main/java/com/community/manager/ManagerController.java
  src/main/java/com/community/manager/ManagerService.java
  src/main/java/com/community/manager/ManagerSettlement.java
  src/main/java/com/community/service/InfoPageService.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-notice-detail.html
  src/main/resources/templates/info/info-notice.html
  src/main/resources/templates/manager-fragments.html
  src/main/resources/templates/manager/m_account.html
  src/main/resources/templates/manager/m_board.html
  src/main/resources/templates/manager/m_main.html
  src/main/resources/templates/manager/maps.html
  src/main/resources/templates/manager/tables.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#415 branch up-to-date
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/domain/board/BoardRepositoryExtension.java
  src/main/java/com/community/domain/board/BoardRepositoryExtensionImpl.java
  src/main/java/com/community/domain/council/CouncilRepository.java
  src/main/java/com/community/domain/inquire/InquireAnswer.java
  src/main/java/com/community/domain/inquire/InquireAnswerRepository.java
  src/main/java/com/community/domain/notice/Notice.java
  src/main/java/com/community/domain/notice/NoticeRepository.java
  src/main/java/com/community/infra/aws/S3.java
  src/main/java/com/community/manager/ManagerController.java
  src/main/java/com/community/manager/ManagerService.java
  src/main/java/com/community/manager/ManagerSettlement.java
  src/main/java/com/community/service/InfoPageService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/board-search.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/council-search.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-faq.html
  src/main/resources/templates/info/info-notice-detail.html
  src/main/resources/templates/info/info-notice.html
  src/main/resources/templates/manager-fragments.html
  src/main/resources/templates/manager/m_account.html
  src/main/resources/templates/manager/m_board.html
  src/main/resources/templates/manager/m_main.html
  src/main/resources/templates/manager/maps.html
  src/main/resources/templates/manager/tables.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#417 branch up-to-date
  README.md
  src/main/java/com/community/domain/study/StudyRepositoryExtensionImpl.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/study/study-list.html
Labels: branch up-to-date

#416 Notice 페이지 수정
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/info/info-notice-detail.html
  src/main/resources/templates/info/info-notice.html
Labels: bug, enhancement

#418 branch up-to-date
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/info/info-notice-detail.html
  src/main/resources/templates/info/info-notice.html
Labels: branch up-to-date

#419 서비스 약관 제거 / Board top5 쿼리 로직 수정중(미완성) / Board 수정 안 되는 버그 수정
  src/main/java/com/community/domain/board/BoardRepositoryExtensionImpl.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/info/info-notice-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix

#420 branch up-to-date
  src/main/java/com/community/domain/board/BoardRepositoryExtensionImpl.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/info/info-notice-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#421 학생회, 공지사항 버그 해결 / Slider 적용 / 프로필 버그 해결 / 리드미 정리
  README.md
  src/main/java/com/community/infra/config/AsyncConfig.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/static/assets/images/11 2.jpeg
  src/main/resources/static/assets/images/11.jpeg
  src/main/resources/static/assets/images/19.jpeg
  src/main/resources/static/assets/images/7.jpeg
  src/main/resources/static/assets/images/8.jpeg
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/profile/view.html
Labels: bug, enhancement, bug fix

#423 Manager 관련 페이지 추가
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/domain/board/ReplyRepository.java
  src/main/java/com/community/domain/report/ReplyReportRepository.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/ManageController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/resources/templates/manager/manager-main.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#424 branch up-to-date
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/domain/board/ReplyRepository.java
  src/main/java/com/community/domain/report/ReplyReportRepository.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/ManageController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/resources/templates/manager/manager-main.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#427 파일들 내용 중에서 필요 없는 메서드 및 참조하지 않는 쓰레기들 정리
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/infra/config/H2ServerConfig.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/StudyController.java
Labels: enhancement

#428 branch up-to-date
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/infra/config/H2ServerConfig.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/StudyController.java
Labels: branch up-to-date

#426 Manager Board 신고초기화 및 삭제 구현 / Security 수정
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/account/AccountType.java
  src/main/java/com/community/domain/report/BoardReportRepository.java
  src/main/java/com/community/infra/config/SecurityConfig.java
  src/main/java/com/community/infra/config/SecurityUser.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/service/ReportService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/java/com/community/web/controller/MainController.java
  src/main/java/com/community/web/controller/ManageController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/java/com/community/web/controller/ReportController.java
  src/main/java/com/community/web/dto/LoginRequest.java
  src/main/resources/static/package-lock.json
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-notice-detail.html
  src/main/resources/templates/info/info-notice.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/manager/manager-board-detail.html
  src/main/resources/templates/manager/manager-main.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#430 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/account/AccountType.java
  src/main/java/com/community/domain/report/BoardReportRepository.java
  src/main/java/com/community/infra/config/SecurityConfig.java
  src/main/java/com/community/infra/config/SecurityUser.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/service/ReportService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/java/com/community/web/controller/MainController.java
  src/main/java/com/community/web/controller/ManageController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/java/com/community/web/controller/ReportController.java
  src/main/java/com/community/web/dto/LoginRequest.java
  src/main/resources/static/package-lock.json
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-notice-detail.html
  src/main/resources/templates/info/info-notice.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/manager/manager-board-detail.html
  src/main/resources/templates/manager/manager-main.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#431 hasRole 적용
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/info/info-notice.html
Labels: enhancement

#432 branch up-to-date
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/info/info-notice.html
Labels: branch up-to-date

#434 #authentication.principal 버그 수정 / BaseController 코드 간소화 / 사용하지 않는 쓰레기 제거 / 문의사항 답변 추가
  src/main/java/com/community/domain/account/UserAccount.java
  src/main/java/com/community/domain/chat/RoomRepository.java
  src/main/java/com/community/domain/inquire/InquireAnswer.java
  src/main/java/com/community/domain/inquire/InquireAnswerRepository.java
  src/main/java/com/community/domain/inquire/InquireRepository.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/service/CouncilService.java
  src/main/java/com/community/service/InfoPageService.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/BookmarkController.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/java/com/community/web/controller/LikeApiController.java
  src/main/java/com/community/web/controller/MainController.java
  src/main/java/com/community/web/controller/ManageController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/java/com/community/web/dto/InquireAnswerForm.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/info/info-contact-detail.html
  src/main/resources/templates/info/info-contact-lists.html
  src/main/resources/templates/info/info-contact.html
  src/main/resources/templates/info/info-notice-detail.html
  src/main/resources/templates/manager/manager-main.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix

#435 branch up-to-date
  src/main/java/com/community/domain/account/UserAccount.java
  src/main/java/com/community/domain/chat/RoomRepository.java
  src/main/java/com/community/domain/inquire/InquireAnswer.java
  src/main/java/com/community/domain/inquire/InquireAnswerRepository.java
  src/main/java/com/community/domain/inquire/InquireRepository.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/service/CouncilService.java
  src/main/java/com/community/service/InfoPageService.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/BookmarkController.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/java/com/community/web/controller/LikeApiController.java
  src/main/java/com/community/web/controller/MainController.java
  src/main/java/com/community/web/controller/ManageController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/java/com/community/web/dto/InquireAnswerForm.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/info/info-contact-detail.html
  src/main/resources/templates/info/info-contact-lists.html
  src/main/resources/templates/info/info-contact.html
  src/main/resources/templates/info/info-notice-detail.html
  src/main/resources/templates/manager/manager-main.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#436 contact View 조정
  src/main/resources/templates/info/info-contact-detail.html
  src/main/resources/templates/info/info-contact-lists.html
  src/main/resources/templates/manager/manager-main.html
Labels: enhancement

#438 branch up-to-date
  src/main/resources/templates/info/info-contact-detail.html
  src/main/resources/templates/info/info-contact-lists.html
  src/main/resources/templates/manager/manager-main.html
Labels: branch up-to-date

#440 Study 명세 수정 / 이메일 체크 로직 졸작탭에 추가
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/infra/aws/S3Service.java
  src/main/java/com/community/web/controller/GraduationController.java
  src/main/resources/templates/graduation/graduation-list.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#441 branch up-to-date
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/infra/aws/S3Service.java
  src/main/java/com/community/web/controller/GraduationController.java
  src/main/resources/templates/graduation/graduation-list.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#443 Leejihoon
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-meetings.html
Labels: enhancement

#444 SearchForm 스터디 -> 동아리 수정
  src/main/java/com/community/web/controller/SearchController.java
  src/main/resources/templates/search/search-form.html
Labels: enhancement

#445 branch up-to-date
  src/main/java/com/community/infra/alarm/StudyEventListener.java
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/index.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/profile/view.html
  src/main/resources/templates/study/settings/alarm.html
  src/main/resources/templates/study/settings/calendar.html
  src/main/resources/templates/study/settings/config.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/members.html
  src/main/resources/templates/study/settings/tags.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/study/study-with-tag.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#446 branch up-to-date
  src/main/java/com/community/infra/alarm/StudyEventListener.java
  src/main/java/com/community/web/controller/SearchController.java
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/profile/view.html
  src/main/resources/templates/search/search-form.html
  src/main/resources/templates/study/settings/alarm.html
  src/main/resources/templates/study/study-with-tag.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#447 logo, logo-mobile 수정
  src/main/resources/static/assets/images/logo-mobile.png
  src/main/resources/static/assets/images/logo.png
Labels: enhancement

#448 notice 뒤로가기 수정
  src/main/resources/templates/info/info-notice-detail.html
Labels: enhancement

#449 branch up-to-date
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/profile/view.html
Labels: branch up-to-date

#450 branch up-to-date
  src/main/resources/static/assets/images/logo-mobile.png
  src/main/resources/static/assets/images/logo.png
  src/main/resources/templates/info/info-notice-detail.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/profile/view.html
Labels: branch up-to-date
