Repository lee-ji-hoon/community, pull requests merged in 2022-03, with the labels that each got.

#89 스터디 일정 및 인원 valid 적용 / 스터디 view, settings 개선
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyRepository.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/validator/StudyFormValidator.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/study/settings/banner.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/study.html
  src/main/resources/templates/study/settings/tags.html
  src/main/resources/templates/study/settings/zones.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/view.html
Labels: enhancement

#92 branch up-to-date
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyRepository.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/validator/StudyFormValidator.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/study/settings/banner.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/study.html
  src/main/resources/templates/study/settings/tags.html
  src/main/resources/templates/study/settings/zones.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/view.html
Labels: branch up-to-date

#94 branch-up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/form/ReplyForm.java
  src/main/java/com/community/like/LikeApiController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/board/board-write.html
  src/main/resources/templates/board/detail-fragments.html
  src/main/resources/templates/board/detail.html
Labels: branch up-to-date

#95 댓글 ajax 작성 버그 수정
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/resources/templates/board/detail-fragments.html
Labels: enhancement, bug fix

#97 gitignore 수정
  .gitignore
  src/main/java/com/community/study/StudyController.java
Labels: enhancement

#102 branch up-to-date
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/like/LikeRepository.java
  src/main/resources/static/assets/js/for-nightmode.js
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/board/board-error.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#103 병합작업
  src/main/java/com/community/MainController.java
  src/main/java/com/community/config/SecurityConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/static/assets/images/logo-mobile.png
  src/main/resources/static/assets/images/logo.png
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/login.html
  src/main/resources/templates/study/members.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#104 병합 작업
  src/main/java/com/community/account/AccountService.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
Labels: enhancement

#105 branch up-to-date
  src/main/java/com/community/account/AccountService.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
Labels: branch up-to-date

#106 디자인 갈이 시작
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#107 branch up-to-date
  src/main/java/com/community/MainController.java
  src/main/java/com/community/config/SecurityConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/static/assets/images/logo-mobile.png
  src/main/resources/static/assets/images/logo.png
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/login.html
  src/main/resources/templates/study/members.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#108 병합 작업
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
Labels: enhancement

#109 회원 및 메인페이지 뷰 수정 진행중
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/config/SecurityConfig.java
  src/main/java/com/community/study/StudyController.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/templates/account/check-email.html
  src/main/resources/templates/account/checked-email.html
  src/main/resources/templates/account/email-login-view.html
  src/main/resources/templates/account/email-login.html
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/account/send-email-link.html
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#110 branch up-to-date
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
Labels: branch up-to-date

#112 merge
  src/main/java/com/community/account/AccountController.java
  src/main/resources/templates/account/email-login-view.html
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#113 branch up-to-date
  src/main/java/com/community/account/AccountController.java
  src/main/resources/templates/account/email-login-view.html
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#114 기능 수정 완료
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/form/BoardForm.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
Labels: enhancement

#115 branch up-to-date
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/form/BoardForm.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
Labels: branch up-to-date

#116 회원 프로필 페이지 작업 중
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/account/AccountService.java
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/config/SecurityConfig.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/form/ProfileForm.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/assets/images/avatars/study-banner.jpeg
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/account/checked-email.html
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/account/send-email-link.html
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#117 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/account/AccountService.java
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/config/SecurityConfig.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/form/ProfileForm.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/assets/images/avatars/study-banner.jpeg
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/account/checked-email.html
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/account/send-email-link.html
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#118 배너 이미지 변경 버그 수정
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/settings/profile-settings.html
Labels: enhancement, bug fix

#119 boardOwner 추가 및 TestDataInit 수정
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
Labels: enhancement

#120 branch up-to-date
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/settings/profile-settings.html
Labels: branch up-to-date

#121 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
Labels: branch up-to-date

#122 게시물 수정 및 삭제 이벤트 추가
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/board/board-error.html
Labels: enhancement

#123 branch up-to-date
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/board/board-error.html
Labels: branch up-to-date

#125 메인 페이지 디자인 및 게시판 버그 수정
  src/main/java/com/community/MainController.java
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/error-page.html
  src/main/resources/templates/index.html
Labels: enhancement, bug fix

#127 branch up-to-date
  src/main/java/com/community/MainController.java
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/error-page.html
  src/main/resources/templates/index.html
Labels: branch up-to-date

#129 포럼 추가 및 수정 진행 중
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/forum/Forum.java
  src/main/java/com/community/forum/ForumController.java
  src/main/java/com/community/forum/ForumForm.java
  src/main/java/com/community/forum/ForumRepository.java
  src/main/java/com/community/forum/ForumService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/forum/forum-detail.html
  src/main/resources/templates/forum/forums.html
Labels: bug, enhancement

#130 branch up-to-date
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/forum/Forum.java
  src/main/java/com/community/forum/ForumController.java
  src/main/java/com/community/forum/ForumForm.java
  src/main/java/com/community/forum/ForumRepository.java
  src/main/java/com/community/forum/ForumService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/forum/forum-detail.html
  src/main/resources/templates/forum/forums.html
Labels: branch up-to-date

#128 스터디 재조정
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/form/StudyForm.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/assets/scss/layout/_profile.scss
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/settings/account.html
  src/main/resources/templates/settings/notifications.html
  src/main/resources/templates/settings/password.html
  src/main/resources/templates/settings/profile-settings.html
  src/main/resources/templates/settings/withdraw.html
  src/main/resources/templates/study/form.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#131 branch up-to-date
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/form/StudyForm.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/assets/scss/layout/_profile.scss
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/settings/account.html
  src/main/resources/templates/settings/notifications.html
  src/main/resources/templates/settings/password.html
  src/main/resources/templates/settings/profile-settings.html
  src/main/resources/templates/settings/withdraw.html
  src/main/resources/templates/study/form.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#132 fragment 수정 및 각 게시판 별로 적용
  src/main/java/com/community/forum/ForumController.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/forum/forum-detail.html
  src/main/resources/templates/forum/forums.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#133 branch up-to-date
  src/main/java/com/community/forum/ForumController.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/forum/forum-detail.html
  src/main/resources/templates/forum/forums.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#135 zones 삭제 및 디비 변경
  build.gradle
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/config/H2ServerConfig.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyRepository.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/zone/Zone.java
  src/main/java/com/community/zone/ZoneForm.java
  src/main/java/com/community/zone/ZoneRepository.java
  src/main/java/com/community/zone/ZoneService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/templates/study/settings/zones.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/view.html
  src/main/resources/templates/theme-fragments.html
  src/main/resources/zones.csv
Labels: bug, duplicate, bug fix

#134 게시글 수정 및 삭제 알람 추가 포럼 write 추가
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/forum/Forum.java
  src/main/java/com/community/forum/ForumController.java
  src/main/java/com/community/forum/ForumReply.java
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/forum/forum-detail.html
  src/main/resources/templates/forum/forum-write.html
  src/main/resources/templates/forum/forums.html
Labels: enhancement, bug fix

#136 branch up-to-date
  build.gradle
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/config/H2ServerConfig.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyRepository.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/zone/Zone.java
  src/main/java/com/community/zone/ZoneForm.java
  src/main/java/com/community/zone/ZoneRepository.java
  src/main/java/com/community/zone/ZoneService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/templates/study/settings/zones.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/view.html
  src/main/resources/templates/theme-fragments.html
  src/main/resources/zones.csv
Labels: branch up-to-date

#137 branch up-to-date
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/forum/Forum.java
  src/main/java/com/community/forum/ForumController.java
  src/main/java/com/community/forum/ForumReply.java
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/forum/forum-detail.html
  src/main/resources/templates/forum/forum-write.html
  src/main/resources/templates/forum/forums.html
Labels: branch up-to-date

#138 Postgre -> H2 DB 변경
  src/main/java/com/community/board/controller/BoardController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/forum/forums.html
  src/main/resources/templates/index.html
Labels: bug, enhancement

#139 프로필 버그 해결 / 스터디 뷰 버그 해결 /
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/account/AccountService.java
  src/main/java/com/community/study/StudyController.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/assets/images/favicon 2.png
  src/main/resources/static/assets/images/favicon.png
  src/main/resources/static/assets/images/logo-mobile.png
  src/main/resources/static/assets/images/logo.png
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/forum/forum-write.html
  src/main/resources/templates/settings/tags.html
  src/main/resources/templates/study/form.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/tags.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/view.html
  src/main/resources/templates/theme-fragments.html
Labels: bug, enhancement, bug fix

#140 branch up-to-date
  src/main/java/com/community/board/controller/BoardController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/forum/forums.html
  src/main/resources/templates/index.html
Labels: branch up-to-date

#141 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/account/AccountService.java
  src/main/java/com/community/study/StudyController.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/assets/images/favicon 2.png
  src/main/resources/static/assets/images/favicon.png
  src/main/resources/static/assets/images/logo-mobile.png
  src/main/resources/static/assets/images/logo.png
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/forum/forum-write.html
  src/main/resources/templates/settings/tags.html
  src/main/resources/templates/study/form.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/tags.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#143 스터디 설정 추가
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/form/StudyCalendarForm.java
  src/main/java/com/community/study/form/StudyDescriptionForm.java
  src/main/java/com/community/study/validator/StudyCalendarFormValidator.java
  src/main/resources/templates/settings/account.html
  src/main/resources/templates/settings/profile-settings.html
  src/main/resources/templates/study/form.html
  src/main/resources/templates/study/settings/calendar.html
  src/main/resources/templates/study/settings/config.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/study.html
  src/main/resources/templates/study/settings/tags.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#144 branch up-to-date
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/form/StudyCalendarForm.java
  src/main/java/com/community/study/form/StudyDescriptionForm.java
  src/main/java/com/community/study/validator/StudyCalendarFormValidator.java
  src/main/resources/templates/settings/account.html
  src/main/resources/templates/settings/profile-settings.html
  src/main/resources/templates/study/form.html
  src/main/resources/templates/study/settings/calendar.html
  src/main/resources/templates/study/settings/config.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/study.html
  src/main/resources/templates/study/settings/tags.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#142 Forum 디자인 수정 및 TDI 데이터 추가
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/forum/Forum.java
  src/main/java/com/community/forum/ForumController.java
  src/main/java/com/community/forum/ForumRepository.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/forum/forum-detail.html
  src/main/resources/templates/forum/forum-write.html
  src/main/resources/templates/forum/forums.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#145 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/forum/Forum.java
  src/main/java/com/community/forum/ForumController.java
  src/main/java/com/community/forum/ForumRepository.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/forum/forum-detail.html
  src/main/resources/templates/forum/forum-write.html
  src/main/resources/templates/forum/forums.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#146 board 리팩터링 및 약간의 디자인 수정
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/entity/Board.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/form/BoardForm.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/forum/Forum.java
  src/main/java/com/community/forum/ForumReply.java
  src/main/java/com/community/like/Likes.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/board/board-fragments.html
  src/main/resources/templates/forum/forum-write.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#147 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/entity/Board.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/form/BoardForm.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/forum/Forum.java
  src/main/java/com/community/forum/ForumReply.java
  src/main/java/com/community/like/Likes.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/board/board-fragments.html
  src/main/resources/templates/forum/forum-write.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#150 branch up-to-date
  build.gradle
  src/main/java/com/community/account/AccountService.java
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/account/repository/AccountRepository.java
  src/main/java/com/community/alarm/Alarm.java
  src/main/java/com/community/alarm/AlarmType.java
  src/main/java/com/community/config/H2ServerConfig.java
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyRepository.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/form/StudyForm.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/package-lock.json
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/study/members.html
  src/main/resources/templates/study/settings/config.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#149 댓글 삭제 및 추가 로직 구현
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/java/com/community/report/ReportController.java
  src/main/java/com/community/report/entity/BoardReport.java
  src/main/java/com/community/report/entity/ReplyReport.java
  src/main/java/com/community/report/form/BoardReportForm.java
  src/main/java/com/community/report/form/ReplyReportForm.java
  src/main/java/com/community/report/service/ReportService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/report-form.html
Labels: bug, enhancement

#152 branch-up-to-date
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/java/com/community/report/ReportController.java
  src/main/java/com/community/report/entity/BoardReport.java
  src/main/java/com/community/report/entity/ReplyReport.java
  src/main/java/com/community/report/form/BoardReportForm.java
  src/main/java/com/community/report/form/ReplyReportForm.java
  src/main/java/com/community/report/service/ReportService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/report-form.html
Labels: branch up-to-date

#154 theme-fragments.html 학생회 매핑 수정
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#156 branch up-to-date
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#155 학생회 Entity 및 View 생성
  src/main/java/com/community/council/Council.java
  src/main/java/com/community/council/CouncilController.java
  src/main/java/com/community/council/CouncilForm.java
  src/main/java/com/community/council/CouncilRepository.java
  src/main/java/com/community/council/CouncilService.java
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/council/council-posts.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/council/student-council.html
  src/main/resources/templates/report-form.html
Labels: enhancement

#157 branch up-to-date
  src/main/java/com/community/council/Council.java
  src/main/java/com/community/council/CouncilController.java
  src/main/java/com/community/council/CouncilForm.java
  src/main/java/com/community/council/CouncilRepository.java
  src/main/java/com/community/council/CouncilService.java
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/council/council-posts.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/council/student-council.html
  src/main/resources/templates/report-form.html
Labels: branch up-to-date

#158 마켓 뷰 수정
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/market/Market.java
  src/main/java/com/community/market/MarketController.java
  src/main/java/com/community/market/MarketForm.java
  src/main/java/com/community/market/MarketItemStatus.java
  src/main/java/com/community/market/MarketRepository.java
  src/main/java/com/community/market/MarketService.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/entity/Meetings.java
  src/main/java/com/community/study/entity/Study.java
  src/main/java/com/community/study/form/MeetingsForm.java
  src/main/java/com/community/study/repository/MeetingsRepository.java
  src/main/java/com/community/study/validator/MeetingFormValidator.java
  src/main/resources/static/assets/css/summernote.min.css
  src/main/resources/static/assets/js/summernote-ko-KR.js
  src/main/resources/static/assets/js/summernote.min.js
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/study/meetings/view.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#159 Council Entity 수정 및 학생회 페이지 디자인 수정
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/java/com/community/council/Council.java
  src/main/java/com/community/council/CouncilController.java
  src/main/java/com/community/council/CouncilForm.java
  src/main/java/com/community/council/CouncilService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/council/council-posts.html
  src/main/resources/templates/council/detail.html
Labels: enhancement

#161 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/java/com/community/council/Council.java
  src/main/java/com/community/council/CouncilController.java
  src/main/java/com/community/council/CouncilForm.java
  src/main/java/com/community/council/CouncilService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/council/council-posts.html
  src/main/resources/templates/council/detail.html
Labels: branch up-to-date

#160 branch up-to-date
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/market/Market.java
  src/main/java/com/community/market/MarketController.java
  src/main/java/com/community/market/MarketForm.java
  src/main/java/com/community/market/MarketItemStatus.java
  src/main/java/com/community/market/MarketRepository.java
  src/main/java/com/community/market/MarketService.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/entity/Meetings.java
  src/main/java/com/community/study/entity/Study.java
  src/main/java/com/community/study/form/MeetingsForm.java
  src/main/java/com/community/study/repository/MeetingsRepository.java
  src/main/java/com/community/study/validator/MeetingFormValidator.java
  src/main/resources/static/assets/css/summernote.min.css
  src/main/resources/static/assets/js/summernote-ko-KR.js
  src/main/resources/static/assets/js/summernote.min.js
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/study/meetings/view.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#162 모임, 마켓 댓글 달기
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/java/com/community/market/Market.java
  src/main/java/com/community/market/MarketController.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/entity/Meetings.java
  src/main/java/com/community/study/repository/MeetingsRepository.java
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/study/study-meetings.html
Labels: enhancement

#163 branch up-to-date
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/java/com/community/market/Market.java
  src/main/java/com/community/market/MarketController.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/entity/Meetings.java
  src/main/java/com/community/study/repository/MeetingsRepository.java
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/study/study-meetings.html
Labels: branch up-to-date

#164 마켓 등록, reply 리팩토링
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/java/com/community/market/MarketController.java
  src/main/java/com/community/market/MarketService.java
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-list.html
Labels: enhancement

#165 ReplyController 수정
  src/main/java/com/community/market/MarketController.java
Labels: enhancement

#166 댓글 업데이트 수정 중
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/report/ReportController.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/lists/lists.html
  src/main/resources/templates/report-form.html
Labels: enhancement

#167 branch up-to-date
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/report/ReportController.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/lists/lists.html
  src/main/resources/templates/report-form.html
Labels: branch up-to-date

#168 branch up-to-date
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/java/com/community/market/MarketController.java
  src/main/java/com/community/market/MarketService.java
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-list.html
Labels: branch up-to-date

#169 커뮤니티, 학생회 종합 수정
  src/main/java/com/community/MainController.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/council/CouncilController.java
  src/main/java/com/community/council/CouncilRepository.java
  src/main/java/com/community/council/CouncilService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/council/council-posts.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix

#170 branch up-to-date
  src/main/java/com/community/MainController.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/council/CouncilController.java
  src/main/java/com/community/council/CouncilRepository.java
  src/main/java/com/community/council/CouncilService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/council/council-posts.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#171 학생회 게시물 수정 및 삭제 구현 완료
  src/main/java/com/community/MainController.java
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/council/CouncilController.java
  src/main/java/com/community/council/CouncilRepository.java
  src/main/java/com/community/council/CouncilService.java
  src/main/java/com/community/lists/ListController.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/templates/council/council-posts.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/lists/lists.html
Labels: enhancement

#172 branch up-to-date
  src/main/java/com/community/MainController.java
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/council/CouncilController.java
  src/main/java/com/community/council/CouncilRepository.java
  src/main/java/com/community/council/CouncilService.java
  src/main/java/com/community/lists/ListController.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/templates/council/council-posts.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/lists/lists.html
Labels: branch up-to-date

#173 스터디 모임 추가 / 모임 별로 태그 지정 가능
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/entity/Meetings.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/study/study-meetings-detail.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/study/study-with-tag.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix

#174 branch up-to-date
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/entity/Meetings.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/study/study-meetings-detail.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/study/study-with-tag.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#175 index 및 report 로직 수정
  .gitignore
  src/main/java/com/community/MainController.java
  src/main/java/com/community/report/ReportController.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/report-form.html
Labels: enhancement

#176 branch up-to-date
  .gitignore
  src/main/java/com/community/MainController.java
  src/main/java/com/community/report/ReportController.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/report-form.html
Labels: branch up-to-date

#178 index 및 study meeting 팩토링
  src/main/java/com/community/MainController.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/entity/Meetings.java
  src/main/java/com/community/study/form/MeetingsForm.java
  src/main/java/com/community/study/repository/MeetingsRepository.java
  src/main/java/com/community/study/repository/StudyRepository.java
  src/main/resources/static/assets/images/favicon 2.png
  src/main/resources/static/assets/images/favicon.png
  src/main/resources/static/assets/images/logo-mobile.png
  src/main/resources/static/assets/images/logo.png
  src/main/resources/templates/index.html
  src/main/resources/templates/study/study-meetings-detail.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#179 branch up-to-date
  src/main/java/com/community/MainController.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/entity/Meetings.java
  src/main/java/com/community/study/form/MeetingsForm.java
  src/main/java/com/community/study/repository/MeetingsRepository.java
  src/main/java/com/community/study/repository/StudyRepository.java
  src/main/resources/static/assets/images/favicon 2.png
  src/main/resources/static/assets/images/favicon.png
  src/main/resources/static/assets/images/logo-mobile.png
  src/main/resources/static/assets/images/logo.png
  src/main/resources/templates/index.html
  src/main/resources/templates/study/study-meetings-detail.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#177 사이드바 버그 수정 및 댓글 디자인 및 중복 등록 방지 로직 추가
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix

#180 branch up-to-date
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#181 학생회 사진 추가
  src/main/resources/static/assets/images/7.jpeg
  src/main/resources/static/assets/images/8.jpeg
  src/main/resources/templates/council/council-posts.html
Labels: enhancement

#182 branch up-to-date
  src/main/resources/static/assets/images/7.jpeg
  src/main/resources/static/assets/images/8.jpeg
  src/main/resources/templates/council/council-posts.html
Labels: branch up-to-date

#183 댓글 수정 로직 변경
  src/main/java/com/community/board/service/ReplyService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/council/council-posts.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/index.html
Labels: enhancement

#184 study-list, view 수정 및 profileimg 수정 버그 해결
  src/main/java/com/community/study/StudyController.java
  src/main/resources/static/assets/images/favicon.png
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/settings/profile-img.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#185 branch up-to-date
  src/main/java/com/community/board/service/ReplyService.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/council/council-posts.html
  src/main/resources/templates/council/detail.html
  src/main/resources/templates/index.html
Labels: branch up-to-date

#186 branch up-to-date
  src/main/java/com/community/study/StudyController.java
  src/main/resources/static/assets/images/favicon.png
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/settings/profile-img.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#187 기획안 발표 이전 짜잘한 수정 내역들
  README.md
  src/main/java/com/community/study/StudyController.java
  src/main/resources/static/assets/images/11 2.jpeg
  src/main/resources/static/assets/images/11.jpeg
  src/main/resources/static/assets/images/19.jpeg
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#188 branch up-to-date
  README.md
  src/main/java/com/community/study/StudyController.java
  src/main/resources/static/assets/images/11 2.jpeg
  src/main/resources/static/assets/images/11.jpeg
  src/main/resources/static/assets/images/19.jpeg
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#190 댓글 작성 수정 삭제 성공
  src/main/java/com/community/study/StudyController.java
  src/main/resources/templates/study/study-meetings.html
Labels: bug, enhancement, bug fix

#189 검색 기능 구현중
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/lists/ListController.java
  src/main/java/com/community/search/SearchController.java
  src/main/java/com/community/search/SearchForm.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/lists/lists.html
  src/main/resources/templates/search/search-form.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix

#191 branch up-to-date
  src/main/java/com/community/study/StudyController.java
  src/main/resources/templates/study/study-meetings.html
Labels: branch up-to-date

#192 branch up-to-date
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/lists/ListController.java
  src/main/java/com/community/search/SearchController.java
  src/main/java/com/community/search/SearchForm.java
  src/main/resources/templates/board/blog-read.html
  src/main/resources/templates/board/blogs.html
  src/main/resources/templates/lists/lists.html
  src/main/resources/templates/search/search-form.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#193 검색 구현 및 파일 Rename
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/council/CouncilController.java
  src/main/java/com/community/council/CouncilRepository.java
  src/main/java/com/community/forum/Forum.java
  src/main/java/com/community/forum/ForumController.java
  src/main/java/com/community/forum/ForumForm.java
  src/main/java/com/community/forum/ForumRepository.java
  src/main/java/com/community/forum/ForumService.java
  src/main/java/com/community/like/Likes.java
  src/main/java/com/community/market/MarketRepository.java
  src/main/java/com/community/search/SearchController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/board-fragments.html
  src/main/resources/templates/board/board-list.html
  src/main/resources/templates/board/board-main.html
  src/main/resources/templates/board/board-write.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/board/detail-fragments.html
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/edit.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/forum/forum-detail.html
  src/main/resources/templates/forum/forum-write.html
  src/main/resources/templates/forum/forums.html
  src/main/resources/templates/search/search-form.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#195 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/council/CouncilController.java
  src/main/java/com/community/council/CouncilRepository.java
  src/main/java/com/community/forum/Forum.java
  src/main/java/com/community/forum/ForumController.java
  src/main/java/com/community/forum/ForumForm.java
  src/main/java/com/community/forum/ForumRepository.java
  src/main/java/com/community/forum/ForumService.java
  src/main/java/com/community/like/Likes.java
  src/main/java/com/community/market/MarketRepository.java
  src/main/java/com/community/search/SearchController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/board-fragments.html
  src/main/resources/templates/board/board-list.html
  src/main/resources/templates/board/board-main.html
  src/main/resources/templates/board/board-write.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/board/detail-fragments.html
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/edit.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/forum/forum-detail.html
  src/main/resources/templates/forum/forum-write.html
  src/main/resources/templates/forum/forums.html
  src/main/resources/templates/search/search-form.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#194 스터디 댓글 구현 / 모임 삭제, 변경 / 모임 알림 추가(웹만 가능)
  .gitignore
  README.md
  build.gradle
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/AccountPredicates.java
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/account/repository/AccountRepository.java
  src/main/java/com/community/alarm/Alarm.java
  src/main/java/com/community/alarm/AlarmRepository.java
  src/main/java/com/community/alarm/AlarmType.java
  src/main/java/com/community/alarm/study/StudyCreatedPublish.java
  src/main/java/com/community/alarm/study/StudyEventListener.java
  src/main/java/com/community/config/AsyncConfig.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/form/AlarmForm.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/entity/Meetings.java
  src/main/java/com/community/study/entity/Study.java
  src/main/java/com/community/study/repository/MeetingsRepository.java
  src/main/java/com/community/study/repository/StudyRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/static/package-lock.json
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/account/study-link.html
  src/main/resources/templates/settings/alarm.html
  src/main/resources/templates/settings/zones.html
  src/main/resources/templates/study/settings/alarm.html
  src/main/resources/templates/study/settings/config.html
  src/main/resources/templates/study/settings/tags.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#196 branch up-to-date
  .gitignore
  README.md
  build.gradle
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/AccountPredicates.java
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/account/repository/AccountRepository.java
  src/main/java/com/community/alarm/Alarm.java
  src/main/java/com/community/alarm/AlarmRepository.java
  src/main/java/com/community/alarm/AlarmType.java
  src/main/java/com/community/alarm/study/StudyCreatedPublish.java
  src/main/java/com/community/alarm/study/StudyEventListener.java
  src/main/java/com/community/config/AsyncConfig.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/form/AlarmForm.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/entity/Meetings.java
  src/main/java/com/community/study/entity/Study.java
  src/main/java/com/community/study/repository/MeetingsRepository.java
  src/main/java/com/community/study/repository/StudyRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/static/package-lock.json
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/account/study-link.html
  src/main/resources/templates/settings/alarm.html
  src/main/resources/templates/settings/zones.html
  src/main/resources/templates/study/settings/alarm.html
  src/main/resources/templates/study/settings/config.html
  src/main/resources/templates/study/settings/tags.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#198 DataBase 변경 및 검색 로직 수정 중
  build.gradle
  src/main/java/com/community/report/entity/BoardReport.java
  src/main/java/com/community/report/entity/ReplyReport.java
  src/main/java/com/community/search/SearchController.java
  src/main/java/com/community/study/repository/StudyRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/templates/search/search-form.html
Labels: enhancement

#197 querydsl / alarm 적용
  .gitignore
  src/main/generated/com/community/account/entity/QAccount.java
  src/main/generated/com/community/account/entity/QPersistentLogins.java
  src/main/generated/com/community/alarm/QAlarm.java
  src/main/generated/com/community/board/entity/QBoard.java
  src/main/generated/com/community/board/entity/QReply.java
  src/main/generated/com/community/council/QCouncil.java
  src/main/generated/com/community/like/QLikes.java
  src/main/generated/com/community/market/QMarket.java
  src/main/generated/com/community/report/entity/QBoardReport.java
  src/main/generated/com/community/report/entity/QReplyReport.java
  src/main/generated/com/community/study/entity/QMeetings.java
  src/main/generated/com/community/study/entity/QStudy.java
  src/main/generated/com/community/tag/QTag.java
  src/main/java/com/community/account/AccountPredicates.java
  src/main/java/com/community/alarm/Alarm.java
  src/main/java/com/community/alarm/AlarmController.java
  src/main/java/com/community/alarm/AlarmRepository.java
  src/main/java/com/community/alarm/AlarmService.java
  src/main/java/com/community/alarm/study/StudyEventListener.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/entity/Study.java
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#199 branch up-to-date
  build.gradle
  src/main/java/com/community/report/entity/BoardReport.java
  src/main/java/com/community/report/entity/ReplyReport.java
  src/main/java/com/community/search/SearchController.java
  src/main/java/com/community/study/repository/StudyRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/templates/search/search-form.html
Labels: branch up-to-date

#200 branch up-to-date
  .gitignore
  src/main/generated/com/community/account/entity/QAccount.java
  src/main/generated/com/community/account/entity/QPersistentLogins.java
  src/main/generated/com/community/alarm/QAlarm.java
  src/main/generated/com/community/board/entity/QBoard.java
  src/main/generated/com/community/board/entity/QReply.java
  src/main/generated/com/community/council/QCouncil.java
  src/main/generated/com/community/like/QLikes.java
  src/main/generated/com/community/market/QMarket.java
  src/main/generated/com/community/report/entity/QBoardReport.java
  src/main/generated/com/community/report/entity/QReplyReport.java
  src/main/generated/com/community/study/entity/QMeetings.java
  src/main/generated/com/community/study/entity/QStudy.java
  src/main/generated/com/community/tag/QTag.java
  src/main/java/com/community/account/AccountPredicates.java
  src/main/java/com/community/alarm/Alarm.java
  src/main/java/com/community/alarm/AlarmController.java
  src/main/java/com/community/alarm/AlarmRepository.java
  src/main/java/com/community/alarm/AlarmService.java
  src/main/java/com/community/alarm/study/StudyEventListener.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/study/entity/Study.java
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#201 H2 -> Mysql DB 변경
  build.gradle
  src/main/java/com/community/search/SearchController.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: enhancement

#202 branch up-to-date
  build.gradle
  src/main/java/com/community/search/SearchController.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: branch up-to-date

#203 쪽지 뷰 생성
  src/main/java/com/community/chat/ChatController.java
  src/main/java/com/community/search/SearchController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: bug, enhancement

#205 branch up-to-date
  .gitignore
  README.md
  src/main/generated/com/community/account/entity/QAccount.java
  src/main/generated/com/community/alarm/QAlarm.java
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/alarm/Alarm.java
  src/main/java/com/community/alarm/AlarmController.java
  src/main/java/com/community/alarm/AlarmRepository.java
  src/main/java/com/community/alarm/AlarmService.java
  src/main/java/com/community/alarm/meeting/MeetingCreatedPublish.java
  src/main/java/com/community/alarm/meeting/MeetingEventListener.java
  src/main/java/com/community/alarm/study/StudyEventListener.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/form/AlarmForm.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/java/com/community/study/StudyController.java
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/index.html
  src/main/resources/templates/settings/alarm.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
Labels: branch up-to-date

#206 스터디/댓글/좋아요 구현 완료
  src/main/generated/com/community/account/entity/QAccount.java
  src/main/generated/com/community/alarm/QAlarm.java
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/account/repository/AccountRepository.java
  src/main/java/com/community/alarm/Alarm.java
  src/main/java/com/community/alarm/AlarmController.java
  src/main/java/com/community/alarm/AlarmRepository.java
  src/main/java/com/community/alarm/AlarmService.java
  src/main/java/com/community/alarm/AlarmType.java
  src/main/java/com/community/alarm/like/LikeCreatePublish.java
  src/main/java/com/community/alarm/like/LikeEventListener.java
  src/main/java/com/community/alarm/meeting/MeetingCreatedPublish.java
  src/main/java/com/community/alarm/meeting/MeetingEventListener.java
  src/main/java/com/community/alarm/meeting/ReplyCreatePublish.java
  src/main/java/com/community/alarm/reply/ReplyCreatePublish.java
  src/main/java/com/community/alarm/reply/ReplyEventListener.java
  src/main/java/com/community/alarm/study/StudyCreatedPublish.java
  src/main/java/com/community/alarm/study/StudyEventListener.java
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/entity/Board.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/java/com/community/council/Council.java
  src/main/java/com/community/like/LikeApiController.java
  src/main/java/com/community/like/LikeService.java
  src/main/java/com/community/like/Likes.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/form/AlarmForm.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/java/com/community/report/entity/BoardReport.java
  src/main/java/com/community/report/entity/ReplyReport.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/entity/Meetings.java
  src/main/java/com/community/study/entity/Study.java
  src/main/java/com/community/tag/Tag.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/settings/alarm.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: bug, enhancement

#211 폴더 위치 수정 및 필요 없는 폴더 삭제
  src/main/java/com/community/web/controller/ChatController.java
Labels: enhancement

#212 branch up-to-date
  src/main/java/com/community/web/controller/ChatController.java
Labels: branch up-to-date

#213 Chat 개발 진행 중
  src/main/generated/com/community/domain/account/QAccount.java
  src/main/generated/com/community/domain/account/QPersistentLogins.java
  src/main/generated/com/community/domain/alarm/QAlarm.java
  src/main/generated/com/community/domain/board/QBoard.java
  src/main/generated/com/community/domain/board/QReply.java
  src/main/generated/com/community/domain/chat/QChat.java
  src/main/generated/com/community/domain/council/QCouncil.java
  src/main/generated/com/community/domain/likes/QLikes.java
  src/main/generated/com/community/domain/market/QMarket.java
  src/main/generated/com/community/domain/report/QBoardReport.java
  src/main/generated/com/community/domain/report/QReplyReport.java
  src/main/generated/com/community/domain/study/QMeetings.java
  src/main/generated/com/community/domain/study/QStudy.java
  src/main/generated/com/community/domain/tag/QTag.java
  src/main/java/com/community/domain/board/ReplyRepository.java
  src/main/java/com/community/domain/chat/Chat.java
  src/main/java/com/community/domain/chat/ChatRepository.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/java/com/community/web/dto/ChatForm.java
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/chat/chats-group.html
  src/main/resources/templates/market/market-detail.html
Labels: bug, enhancement

#214 branch up-to-date
  src/main/generated/com/community/domain/account/QAccount.java
  src/main/generated/com/community/domain/account/QPersistentLogins.java
  src/main/generated/com/community/domain/alarm/QAlarm.java
  src/main/generated/com/community/domain/board/QBoard.java
  src/main/generated/com/community/domain/board/QReply.java
  src/main/generated/com/community/domain/chat/QChat.java
  src/main/generated/com/community/domain/council/QCouncil.java
  src/main/generated/com/community/domain/likes/QLikes.java
  src/main/generated/com/community/domain/market/QMarket.java
  src/main/generated/com/community/domain/report/QBoardReport.java
  src/main/generated/com/community/domain/report/QReplyReport.java
  src/main/generated/com/community/domain/study/QMeetings.java
  src/main/generated/com/community/domain/study/QStudy.java
  src/main/generated/com/community/domain/tag/QTag.java
  src/main/java/com/community/domain/board/ReplyRepository.java
  src/main/java/com/community/domain/chat/Chat.java
  src/main/java/com/community/domain/chat/ChatRepository.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/java/com/community/web/dto/ChatForm.java
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/chat/chats-group.html
  src/main/resources/templates/market/market-detail.html
Labels: branch up-to-date

#216 장터 쪽지 보내기 구현 완료
  src/main/java/com/community/web/controller/ChatController.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/market/market-detail.html
Labels: enhancement

#215 QA 버그 해결 및 보류 사항 / alarm
  .gitignore
  build.gradle
  src/main/generated/com/community/domain/account/QAccount.java
  src/main/generated/com/community/domain/account/QPersistentLogins.java
  src/main/generated/com/community/domain/alarm/QAlarm.java
  src/main/generated/com/community/domain/board/QBoard.java
  src/main/generated/com/community/domain/board/QReply.java
  src/main/generated/com/community/domain/chat/QChat.java
  src/main/generated/com/community/domain/council/QCouncil.java
  src/main/generated/com/community/domain/likes/QLikes.java
  src/main/generated/com/community/domain/market/QMarket.java
  src/main/generated/com/community/domain/report/QBoardReport.java
  src/main/generated/com/community/domain/report/QReplyReport.java
  src/main/generated/com/community/domain/study/QMeetings.java
  src/main/generated/com/community/domain/study/QStudy.java
  src/main/generated/com/community/domain/tag/QTag.java
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/alarm/AlarmRepository.java
  src/main/java/com/community/domain/board/Reply.java
  src/main/java/com/community/domain/board/ReplyRepository.java
  src/main/java/com/community/domain/meetings/Meetings.java
  src/main/java/com/community/domain/meetings/MeetingsRepository.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/domain/study/StudyRepository.java
  src/main/java/com/community/domain/study/StudyRepositoryExtension.java
  src/main/java/com/community/domain/study/StudyRepositoryExtensionImpl.java
  src/main/java/com/community/infra/alarm/LikeEventListener.java
  src/main/java/com/community/infra/alarm/MeetingCreatedPublish.java
  src/main/java/com/community/infra/alarm/MeetingEventListener.java
  src/main/java/com/community/infra/alarm/ReplyEventListener.java
  src/main/java/com/community/infra/alarm/StudyEventListener.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/service/AlarmService.java
  src/main/java/com/community/service/ReplyService.java
  src/main/java/com/community/service/StudyService.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/ReportController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/static/package-lock.json
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/index.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/settings/alarm.html
  src/main/resources/templates/study/settings/alarm.html
  src/main/resources/templates/study/settings/calendar.html
  src/main/resources/templates/study/settings/config.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
  src/test/java/com/community/account/AccountControllerTest.java
  src/test/java/com/community/account/MainControllerTest.java
Labels: enhancement

#218 branch up-to-date
  .gitignore
  build.gradle
  src/main/generated/com/community/domain/account/QAccount.java
  src/main/generated/com/community/domain/account/QPersistentLogins.java
  src/main/generated/com/community/domain/alarm/QAlarm.java
  src/main/generated/com/community/domain/board/QBoard.java
  src/main/generated/com/community/domain/board/QReply.java
  src/main/generated/com/community/domain/chat/QChat.java
  src/main/generated/com/community/domain/council/QCouncil.java
  src/main/generated/com/community/domain/likes/QLikes.java
  src/main/generated/com/community/domain/market/QMarket.java
  src/main/generated/com/community/domain/report/QBoardReport.java
  src/main/generated/com/community/domain/report/QReplyReport.java
  src/main/generated/com/community/domain/study/QMeetings.java
  src/main/generated/com/community/domain/study/QStudy.java
  src/main/generated/com/community/domain/tag/QTag.java
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/alarm/AlarmRepository.java
  src/main/java/com/community/domain/board/Reply.java
  src/main/java/com/community/domain/board/ReplyRepository.java
  src/main/java/com/community/domain/meetings/Meetings.java
  src/main/java/com/community/domain/meetings/MeetingsRepository.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/domain/study/StudyRepository.java
  src/main/java/com/community/domain/study/StudyRepositoryExtension.java
  src/main/java/com/community/domain/study/StudyRepositoryExtensionImpl.java
  src/main/java/com/community/infra/alarm/LikeEventListener.java
  src/main/java/com/community/infra/alarm/MeetingCreatedPublish.java
  src/main/java/com/community/infra/alarm/MeetingEventListener.java
  src/main/java/com/community/infra/alarm/ReplyEventListener.java
  src/main/java/com/community/infra/alarm/StudyEventListener.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/service/AlarmService.java
  src/main/java/com/community/service/ReplyService.java
  src/main/java/com/community/service/StudyService.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/ReportController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/static/package-lock.json
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/index.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/settings/alarm.html
  src/main/resources/templates/study/settings/alarm.html
  src/main/resources/templates/study/settings/calendar.html
  src/main/resources/templates/study/settings/config.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
  src/test/java/com/community/account/AccountControllerTest.java
  src/test/java/com/community/account/MainControllerTest.java
Labels: branch up-to-date

#219 alarm 버그 해결 / account Entity 학년, 전공 추가
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/board/Reply.java
  src/main/java/com/community/domain/board/ReplyRepository.java
  src/main/java/com/community/domain/study/Meetings.java
  src/main/java/com/community/domain/study/MeetingsRepository.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/infra/alarm/MeetingCreatedPublish.java
  src/main/java/com/community/infra/alarm/MeetingEventListener.java
  src/main/java/com/community/infra/alarm/ReplyEventListener.java
  src/main/java/com/community/service/AlarmService.java
  src/main/java/com/community/service/ProfileService.java
  src/main/java/com/community/service/ReplyService.java
  src/main/java/com/community/service/StudyService.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/ReportController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/java/com/community/web/dto/ProfileForm.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/settings/profile-img.html
  src/main/resources/templates/settings/profile-settings.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#220 QA 수정 사안 적용
  src/main/java/com/community/domain/chat/Chat.java
  src/main/java/com/community/domain/chat/ChatRepository.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
Labels: enhancement, bug fix

#221 branch up-to-date
  src/main/java/com/community/domain/chat/Chat.java
  src/main/java/com/community/domain/chat/ChatRepository.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
Labels: branch up-to-date

#222 profile-view
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/service/StudyService.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/dto/ProfileForm.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/settings/password.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#224 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/board/Reply.java
  src/main/java/com/community/domain/board/ReplyRepository.java
  src/main/java/com/community/domain/study/Meetings.java
  src/main/java/com/community/domain/study/MeetingsRepository.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/infra/alarm/MeetingCreatedPublish.java
  src/main/java/com/community/infra/alarm/MeetingEventListener.java
  src/main/java/com/community/infra/alarm/ReplyEventListener.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/service/AlarmService.java
  src/main/java/com/community/service/ProfileService.java
  src/main/java/com/community/service/ReplyService.java
  src/main/java/com/community/service/StudyService.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/ReportController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/java/com/community/web/dto/ProfileForm.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/settings/password.html
  src/main/resources/templates/settings/profile-img.html
  src/main/resources/templates/settings/profile-settings.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#223 쪽지 로직 수정 및 추가 작업
  src/main/java/com/community/domain/chat/Chat.java
  src/main/java/com/community/domain/chat/ChatRepository.java
  src/main/java/com/community/domain/chat/Room.java
  src/main/java/com/community/domain/chat/RoomRepository.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/market/market-detail.html
Labels: bug, enhancement, bug fix

#225 branch up-to-date
  src/main/java/com/community/domain/chat/Chat.java
  src/main/java/com/community/domain/chat/ChatRepository.java
  src/main/java/com/community/domain/chat/Room.java
  src/main/java/com/community/domain/chat/RoomRepository.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/market/market-detail.html
Labels: branch up-to-date

#226 singUp 이메일 로직 / 로그인 로직 변경
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/UserAccount.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/java/com/community/web/dto/SignUpForm.java
  src/main/resources/application-dev.properties
  src/main/resources/static/assets/css/style.css
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/study/settings/members.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#227 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/UserAccount.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/java/com/community/web/dto/SignUpForm.java
  src/main/resources/application-dev.properties
  src/main/resources/static/assets/css/style.css
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/study/settings/members.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#228 Profile 쪽지 추가 및 쪽지 로직 수정
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/market/market-detail.html
Labels: enhancement

#229 branch-up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/market/market-detail.html
Labels: branch up-to-date

#230 Chat View 추가 및 수정
  src/main/resources/templates/chat/chat-detail.html
Labels: enhancement, bug fix

#231 branch-up-to-date
  src/main/resources/templates/chat/chat-detail.html
Labels: branch up-to-date

#234 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/service/StudyService.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/members.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#233 Chat ReadChk 구현 및 View 수정
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: bug, enhancement

#235 branch-up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#236 전역 Controller 생성 및 쪽지 ReadChk 버그 수정
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/chat/ChatRepository.java
  src/main/java/com/community/domain/chat/Room.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix

#237 branch-up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/chat/ChatRepository.java
  src/main/java/com/community/domain/chat/Room.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#238 자동 로그인 버그 해결 / 종료된 스터디 view에서 삭제 / 알림 전역 컨트롤러로 변경
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/account/UserAccount.java
  src/main/java/com/community/domain/alarm/AlarmRepository.java
  src/main/java/com/community/infra/alarm/LikeEventListener.java
  src/main/java/com/community/infra/alarm/MeetingEventListener.java
  src/main/java/com/community/infra/alarm/ReplyEventListener.java
  src/main/java/com/community/infra/alarm/StudyEventListener.java
  src/main/java/com/community/service/AlarmService.java
  src/main/java/com/community/service/ProfileService.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/static/package-lock.json
  src/main/resources/templates/theme-fragments.html
Labels: bug, enhancement

#239 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/account/UserAccount.java
  src/main/java/com/community/domain/alarm/AlarmRepository.java
  src/main/java/com/community/infra/alarm/LikeEventListener.java
  src/main/java/com/community/infra/alarm/MeetingEventListener.java
  src/main/java/com/community/infra/alarm/ReplyEventListener.java
  src/main/java/com/community/infra/alarm/StudyEventListener.java
  src/main/java/com/community/service/AlarmService.java
  src/main/java/com/community/service/ProfileService.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/static/package-lock.json
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#240 Chat 날짜별로 묶음 추가
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/resources/application-dev.properties
  src/main/resources/static/assets/css/style.css
  src/main/resources/templates/chat/chat-detail.html
Labels: enhancement

#241 branch-up-to-date
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/resources/application-dev.properties
  src/main/resources/static/assets/css/style.css
  src/main/resources/templates/chat/chat-detail.html
Labels: branch up-to-date
