Repository lee-ji-hoon/community, pull requests merged in 2022-04, with the labels that each got.

#244 team Email 생성 및 연동
  src/main/resources/application-dev.properties
Labels: enhancement

#245 properties mysql 주소 변경
  src/main/resources/application.properties
Labels: enhancement

#246 branch up-to-date
  src/main/resources/application-dev.properties
Labels: branch up-to-date

#247 json 점검 중
  .gitignore
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
Labels: enhancement

#248 branch up-to-date
  .gitignore
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
Labels: branch up-to-date

#249 profile 버그 해결
  src/main/java/com/community/domain/account/Account.java
  src/main/resources/static/package-lock.json
  src/main/resources/templates/account/profile.html
Labels: enhancement

#250 이메일 인증 로직 추가 / AlarmService 로직 단순화 및 전역 컨트롤러와의 충돌 해결
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/account/check-email.html
  src/main/resources/templates/account/checked-email.html
  src/main/resources/templates/account/email-login-view.html
  src/main/resources/templates/account/email-login.html
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/account/send-email-link.html
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/index.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#252 branch up-to-date
  .gitignore
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/application.properties
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/account/check-email.html
  src/main/resources/templates/account/checked-email.html
  src/main/resources/templates/account/email-login-view.html
  src/main/resources/templates/account/email-login.html
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/account/send-email-link.html
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/settings/alarm.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#253 이메일 인증 로직 / AWS s3 / dev-properties ignore
  .gitignore
  build.gradle
  src/main/java/com/community/domain/market/Market.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/service/S3Service.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/dto/MarketForm.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#254 branch up-to-date
  .gitignore
  build.gradle
  src/main/java/com/community/domain/market/Market.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/service/S3Service.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/dto/MarketForm.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#255 dev 임시 추가
  .gitignore
  src/main/resources/application-dev.properties
Labels: enhancement

#256 branch up-to-date
  .gitignore
  src/main/resources/application-dev.properties
Labels: branch up-to-date

#257 properties 통합
  src/main/resources/application.properties
Labels: enhancement

#258 branch up-to-date
  src/test/java/com/community/AppTests.java
Labels: branch up-to-date

#259 branch up-to-date
  src/main/resources/application.properties
  src/test/java/com/community/AppTests.java
Labels: branch up-to-date

#260 java Assist Gradle 추가
  build.gradle
  src/main/resources/application.properties
Labels: enhancement

#261 Chat 뷰 수정
  src/main/java/com/community/domain/chat/Chat.java
  src/main/resources/templates/board/board-detail.html
Labels: enhancement

#262 branch up-to-date
  build.gradle
  src/main/java/com/community/domain/chat/Chat.java
  src/main/resources/application.properties
  src/main/resources/templates/board/board-detail.html
Labels: branch up-to-date

#263 market form 분리 및 로직 변경 / properties RDS 권한자 변경
  src/main/java/com/community/web/controller/MarketController.java
  src/main/resources/application.properties
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
Labels: enhancement

#264 branch up-to-date
  src/main/java/com/community/web/controller/MarketController.java
  src/main/resources/application.properties
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
Labels: branch up-to-date

#266 branch up-to-date
  src/main/java/com/community/web/controller/BaseController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/login-form.html
  src/main/resources/templates/market/market-form.html
Labels: branch up-to-date

#267 html lang 변환 / market image upload 성공
  src/main/resources/templates/account/check-email.html
  src/main/resources/templates/account/checked-email.html
  src/main/resources/templates/account/email-login-view.html
  src/main/resources/templates/account/email-login.html
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/account/send-email-link.html
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/account/study-link.html
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/chat/chats-group.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/error-page.html
  src/main/resources/templates/index.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/info/info-contact.html
  src/main/resources/templates/info/info-privacy.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/report-form.html
  src/main/resources/templates/search/search-form.html
  src/main/resources/templates/settings/account.html
  src/main/resources/templates/settings/alarm.html
  src/main/resources/templates/settings/password.html
  src/main/resources/templates/settings/profile-img.html
  src/main/resources/templates/settings/profile-settings.html
  src/main/resources/templates/settings/tags.html
  src/main/resources/templates/settings/withdraw.html
  src/main/resources/templates/study/settings/alarm.html
  src/main/resources/templates/study/settings/calendar.html
  src/main/resources/templates/study/settings/config.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/members.html
  src/main/resources/templates/study/settings/tags.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-meetings-detail.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/study/study-with-tag.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#268 branch up-to-date
  src/main/resources/templates/account/check-email.html
  src/main/resources/templates/account/checked-email.html
  src/main/resources/templates/account/email-login-view.html
  src/main/resources/templates/account/email-login.html
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/account/send-email-link.html
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/account/study-link.html
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/chat/chats-group.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/error-page.html
  src/main/resources/templates/index.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/info/info-contact.html
  src/main/resources/templates/info/info-privacy.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/report-form.html
  src/main/resources/templates/search/search-form.html
  src/main/resources/templates/settings/account.html
  src/main/resources/templates/settings/alarm.html
  src/main/resources/templates/settings/password.html
  src/main/resources/templates/settings/profile-img.html
  src/main/resources/templates/settings/profile-settings.html
  src/main/resources/templates/settings/tags.html
  src/main/resources/templates/settings/withdraw.html
  src/main/resources/templates/study/settings/alarm.html
  src/main/resources/templates/study/settings/calendar.html
  src/main/resources/templates/study/settings/config.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/members.html
  src/main/resources/templates/study/settings/tags.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-meetings-detail.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/study/study-with-tag.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#269 jdenticon -> identicon 변경 / cloud front 적용 / market-imge 성공
  src/main/java/com/community/service/S3Service.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/chat/chats-group.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/study/study-meetings-detail.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#270 Manager 페이지 추가
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/manager/ManagerController.java
  src/main/java/com/community/manager/ManagerService.java
  src/main/resources/static/assets/img/angular.jpg
  src/main/resources/static/assets/img/apple-icon.png
  src/main/resources/static/assets/img/bootstrap.jpg
  src/main/resources/static/assets/img/component-btn-pink.png
  src/main/resources/static/assets/img/component-btn.png
  src/main/resources/static/assets/img/component-info-2.png
  src/main/resources/static/assets/img/component-info-card.png
  src/main/resources/static/assets/img/component-menu.png
  src/main/resources/static/assets/img/component-profile-card.png
  src/main/resources/static/assets/img/documentation.png
  src/main/resources/static/assets/img/favicon.ico
  src/main/resources/static/assets/img/github.svg
  src/main/resources/static/assets/img/google.svg
  src/main/resources/static/assets/img/ill_header.png
  src/main/resources/static/assets/img/ill_header_3.png
  src/main/resources/static/assets/img/landing.jpg
  src/main/resources/static/assets/img/login.jpg
  src/main/resources/static/assets/img/pattern_react.png
  src/main/resources/static/assets/img/profile.jpg
  src/main/resources/static/assets/img/react.jpg
  src/main/resources/static/assets/img/register_bg_2.png
  src/main/resources/static/assets/img/sketch.jpg
  src/main/resources/static/assets/img/team-1-800x800.jpg
  src/main/resources/static/assets/img/team-1-800x8000.jpg
  src/main/resources/static/assets/img/team-2-800x800.jpg
  src/main/resources/static/assets/img/team-3-800x800.jpg
  src/main/resources/static/assets/img/team-4-470x470.png
  src/main/resources/static/assets/img/vue.jpg
  src/main/resources/static/assets/styles/index.css
  src/main/resources/static/assets/styles/tailwind.css
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-brands-400.eot
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-brands-400.svg
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-brands-400.ttf
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-brands-400.woff
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-brands-400.woff2
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-regular-400.eot
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-regular-400.svg
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-regular-400.ttf
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-regular-400.woff
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-regular-400.woff2
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-solid-900.eot
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-solid-900.svg
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-solid-900.ttf
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2
  src/main/resources/templates/manager-fragments.html
  src/main/resources/templates/manager/m_board.html
  src/main/resources/templates/manager/m_main.html
  src/main/resources/templates/manager/maps.html
  src/main/resources/templates/manager/settings.html
  src/main/resources/templates/manager/tables.html
Labels: enhancement

#271 branch up-to-date
  src/main/java/com/community/service/S3Service.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/chat/chats-group.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/study/study-meetings-detail.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#272 branch up-to-date
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/manager/ManagerController.java
  src/main/java/com/community/manager/ManagerService.java
  src/main/resources/static/assets/img/angular.jpg
  src/main/resources/static/assets/img/apple-icon.png
  src/main/resources/static/assets/img/bootstrap.jpg
  src/main/resources/static/assets/img/component-btn-pink.png
  src/main/resources/static/assets/img/component-btn.png
  src/main/resources/static/assets/img/component-info-2.png
  src/main/resources/static/assets/img/component-info-card.png
  src/main/resources/static/assets/img/component-menu.png
  src/main/resources/static/assets/img/component-profile-card.png
  src/main/resources/static/assets/img/documentation.png
  src/main/resources/static/assets/img/favicon.ico
  src/main/resources/static/assets/img/github.svg
  src/main/resources/static/assets/img/google.svg
  src/main/resources/static/assets/img/ill_header.png
  src/main/resources/static/assets/img/ill_header_3.png
  src/main/resources/static/assets/img/landing.jpg
  src/main/resources/static/assets/img/login.jpg
  src/main/resources/static/assets/img/pattern_react.png
  src/main/resources/static/assets/img/profile.jpg
  src/main/resources/static/assets/img/react.jpg
  src/main/resources/static/assets/img/register_bg_2.png
  src/main/resources/static/assets/img/sketch.jpg
  src/main/resources/static/assets/img/team-1-800x800.jpg
  src/main/resources/static/assets/img/team-1-800x8000.jpg
  src/main/resources/static/assets/img/team-2-800x800.jpg
  src/main/resources/static/assets/img/team-3-800x800.jpg
  src/main/resources/static/assets/img/team-4-470x470.png
  src/main/resources/static/assets/img/vue.jpg
  src/main/resources/static/assets/styles/index.css
  src/main/resources/static/assets/styles/tailwind.css
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-brands-400.eot
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-brands-400.svg
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-brands-400.ttf
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-brands-400.woff
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-brands-400.woff2
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-regular-400.eot
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-regular-400.svg
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-regular-400.ttf
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-regular-400.woff
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-regular-400.woff2
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-solid-900.eot
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-solid-900.svg
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-solid-900.ttf
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff
  src/main/resources/static/assets/vendor/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2
  src/main/resources/templates/manager-fragments.html
  src/main/resources/templates/manager/m_board.html
  src/main/resources/templates/manager/m_main.html
  src/main/resources/templates/manager/maps.html
  src/main/resources/templates/manager/settings.html
  src/main/resources/templates/manager/tables.html
Labels: branch up-to-date

#273 identicon 버그 해결
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#274 branch up-to-date
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#275 Kajunyoung
  src/main/java/com/community/manager/ManagerController.java
  src/main/java/com/community/manager/ManagerService.java
  src/main/java/com/community/manager/ManagerSettlement.java
  src/main/resources/templates/manager-fragments.html
Labels: enhancement

#276 branch up-to-date
  .gitignore
  src/main/java/com/community/manager/ManagerController.java
  src/main/java/com/community/manager/ManagerService.java
  src/main/java/com/community/manager/ManagerSettlement.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/manager-fragments.html
Labels: branch up-to-date

#277 branch up-to-date
  .gitignore
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: branch up-to-date

#279 branch up-to-date
  .gitignore
  src/main/java/com/community/domain/market/Market.java
  src/main/java/com/community/infra/mail/HtmlEmailService.java
  src/main/java/com/community/service/S3Service.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/resources/application.properties
  src/main/resources/static/package-lock.json
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#280 Chrome 브라우저 제외 로직 추가, TDI 수정, Chat Identicon 로직 추가
  src/main/java/com/community/TestDataInit.java
  src/main/resources/application.properties
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#282 Chrome 로직 Mobile Chrome 추가 및 safari 추가
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#283 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/market/Market.java
  src/main/java/com/community/infra/mail/HtmlEmailService.java
  src/main/java/com/community/service/S3Service.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/resources/application.properties
  src/main/resources/static/package-lock.json
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#284 branch up-to-date
  src/main/java/com/community/service/ProfileService.java
  src/main/java/com/community/service/S3Service.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/settings/profile-img.html
Labels: branch up-to-date

#285 branch up-to-date
  src/main/java/com/community/service/S3Service.java
Labels: branch up-to-date

#286 branch up-to-date
  src/main/java/com/community/service/S3Service.java
Labels: branch up-to-date

#287 브라우저 체킹 로직 수정
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#289 branch up-to-date
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#291 market, profile 이메일 인증 Valid 추가
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/login-form.html
  src/main/resources/templates/market/market-detail.html
Labels: enhancement

#294 Summernote 동일화 작업 진행
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/study-form.html
Labels: enhancement

#296 Chat Delay ms 수정
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/study/study-meetings-detail.html
  src/main/resources/templates/study/study-meetings.html
Labels: enhancement

#297 2차 발표 이전 view 수정 (study/account_image) / email 로직 변경
  src/main/java/com/community/web/controller/AccountController.java
  src/main/resources/templates/account/check-email.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#298 branch up-to-date
  src/main/java/com/community/web/controller/AccountController.java
  src/main/resources/templates/account/check-email.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#299 view의 image들 크기 수정 / study-tag 검색 오류 해결
  src/main/resources/templates/index.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#300 board 및 council 내용 수정
  src/main/resources/static/images/46.jpeg
  src/main/resources/static/images/59.jpeg
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
Labels: enhancement

#302 branch up-to-date
  src/main/resources/static/images/46.jpeg
  src/main/resources/static/images/59.jpeg
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-meetings-detail.html
  src/main/resources/templates/study/study-meetings.html
Labels: branch up-to-date

#301 branch up-to-date
  src/main/resources/templates/index.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#304 study-list 버그 해결 및 sidebar 수정
  src/main/java/com/community/infra/alarm/StudyEventListener.java
  src/main/java/com/community/service/StudyService.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/MainController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/study/settings/members.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#303 좋아요 아이콘 변경
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/info/info-contact.html
  src/main/resources/templates/info/info-privacy.html
Labels: enhancement

#306 branch up-to-date
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/info/info-contact.html
  src/main/resources/templates/info/info-privacy.html
Labels: branch up-to-date

#308 chat 버그 수정 및 쪽지 최소 글자 수정
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/market/market-detail.html
Labels: enhancement

#310 theme-fragments 이미지 깨지는거 수정
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix

#311 프로필 스터디 이미지 수정 / 쪽지 테스트
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#312 쪽지 테스트
  src/main/java/com/community/Community.java
  src/main/resources/templates/chat/chat-detail.html
Labels: enhancement

#313 branch up-to-date
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#314 branch up-to-date
  src/main/java/com/community/Community.java
  src/main/java/com/community/domain/alarm/AlarmRepository.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#315 쪽지 날짜별로 묶음 추가 + 알림 개수 최대 지정
  src/main/java/com/community/domain/alarm/AlarmRepository.java
  src/main/java/com/community/domain/chat/RoomRepository.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#317 쪽지 알림 로직 추가
  src/main/java/com/community/web/controller/BaseController.java
Labels: enhancement

#318 회원가입 부분 해결
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#320 마켓 3자리 컴마 구분
  src/main/resources/templates/market/market-detail.html
Labels: enhancement

#321 branch up-to-date
  src/main/java/com/community/domain/alarm/AlarmRepository.java
  src/main/java/com/community/domain/chat/RoomRepository.java
  src/main/java/com/community/service/ChatService.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/chat/chat-detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#323 market image delete 버그 해결 / s3 CloudFront로 접근 / market 페이징 작업 진행중
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/market/Market.java
  src/main/java/com/community/domain/market/MarketItemStatus.java
  src/main/java/com/community/domain/market/MarketRepository.java
  src/main/java/com/community/domain/market/MarketRepositoryExtension.java
  src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/service/ProfileService.java
  src/main/java/com/community/service/S3Service.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/theme-fragments.html
Labels: bug, enhancement

#324 branch up-to-date
  README.md
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/market/Market.java
  src/main/java/com/community/domain/market/MarketItemStatus.java
  src/main/java/com/community/domain/market/MarketRepository.java
  src/main/java/com/community/domain/market/MarketRepositoryExtension.java
  src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/service/ProfileService.java
  src/main/java/com/community/service/S3Service.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#326 Council 페이징 처리(공지만) / Board 수정 로직 변경(ajax 제거)
  src/main/java/com/community/domain/board/Board.java
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/domain/council/Council.java
  src/main/java/com/community/domain/council/CouncilRepository.java
  src/main/java/com/community/manager/ManagerController.java
  src/main/java/com/community/manager/ManagerService.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/service/CouncilService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/java/com/community/web/dto/BoardForm.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/manager-fragments.html
Labels: bug, enhancement

#325 csrf 토큰 설정 / 페이징 작업 중
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/infra/config/SecurityConfig.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/java/com/community/web/dto/MarketForm.java
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
Labels: enhancement, bug fix

#327 branch up-to-date
  src/main/java/com/community/domain/board/Board.java
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/domain/council/Council.java
  src/main/java/com/community/domain/council/CouncilRepository.java
  src/main/java/com/community/manager/ManagerController.java
  src/main/java/com/community/manager/ManagerService.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/service/CouncilService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/java/com/community/web/dto/BoardForm.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/manager-fragments.html
Labels: branch up-to-date

#328 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/infra/config/SecurityConfig.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/java/com/community/web/dto/MarketForm.java
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
Labels: branch up-to-date

#329 Council 페이징 처리(notice)
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/council/councils.html
Labels: bug, enhancement

#331 branch up-to-date
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/council/councils.html
Labels: branch up-to-date

#332 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/alarm/AlarmRepository.java
  src/main/java/com/community/domain/alarm/AlarmType.java
  src/main/java/com/community/domain/market/MarketRepositoryExtension.java
  src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/infra/alarm/LikeEventListener.java
  src/main/java/com/community/infra/alarm/MeetingEventListener.java
  src/main/java/com/community/infra/alarm/ReplyEventListener.java
  src/main/java/com/community/infra/alarm/StudyEventListener.java
  src/main/java/com/community/infra/config/SecurityConfig.java
  src/main/java/com/community/service/ReplyService.java
  src/main/java/com/community/service/StudyService.java
  src/main/java/com/community/web/controller/AccountController.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/manager-fragments.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/profile/settings/account.html
  src/main/resources/templates/profile/settings/alarm.html
  src/main/resources/templates/profile/settings/password.html
  src/main/resources/templates/profile/settings/profile-img.html
  src/main/resources/templates/profile/settings/profile-settings.html
  src/main/resources/templates/profile/settings/tags.html
  src/main/resources/templates/profile/settings/withdraw.html
  src/main/resources/templates/profile/view.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#334 profile 작업 진행 중
  src/main/java/com/community/domain/market/Market.java
  src/main/java/com/community/domain/market/MarketRepository.java
  src/main/java/com/community/domain/market/MarketRepositoryExtension.java
  src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/java/com/community/web/controller/SearchController.java
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/profile/view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#335 branch up-to-date
  src/main/java/com/community/domain/board/ReplyRepository.java
  src/main/java/com/community/service/ReplyService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/councils.html
Labels: branch up-to-date

#341 study 페이징 작업
  README.md
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/study/StudyRepository.java
  src/main/java/com/community/domain/study/StudyRepositoryExtension.java
  src/main/java/com/community/domain/study/StudyRepositoryExtensionImpl.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/study/study-list.html
Labels: enhancement

#343 branch up-to-date
  README.md
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/study/StudyRepository.java
  src/main/java/com/community/domain/study/StudyRepositoryExtension.java
  src/main/java/com/community/domain/study/StudyRepositoryExtensionImpl.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/study/study-list.html
Labels: branch up-to-date

#342 Profile Board+Pagination 적용 / View 단 좋아요, 댓글 로직 변경
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/profile/view.html
Labels: enhancement

#344 branch up-to-date
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/profile/view.html
Labels: branch up-to-date

#345 실시간 인기글 로직 수정
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
Labels: enhancement

#346 branch up-to-date
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
Labels: branch up-to-date

#347 Top5 Boards 로직 변경 / Index 부분 제거 및 링크 수정 / Manager View 수정 및 로직 추가
  src/main/java/com/community/manager/ManagerController.java
  src/main/java/com/community/manager/ManagerService.java
  src/main/java/com/community/web/controller/MainController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/manager-fragments.html
  src/main/resources/templates/manager/m_board.html
  src/main/resources/templates/manager/m_main.html
  src/main/resources/templates/manager/maps.html
  src/main/resources/templates/manager/settings.html
  src/main/resources/templates/manager/tables.html
Labels: enhancement

#348 branch up-to-date
  src/main/java/com/community/manager/ManagerController.java
  src/main/java/com/community/manager/ManagerService.java
  src/main/java/com/community/web/controller/MainController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/manager-fragments.html
  src/main/resources/templates/manager/m_board.html
  src/main/resources/templates/manager/m_main.html
  src/main/resources/templates/manager/maps.html
  src/main/resources/templates/manager/settings.html
  src/main/resources/templates/manager/tables.html
Labels: branch up-to-date

#349 프로빌 이미지 버그 해결 / aws s3 폴더 리팩토링
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/account/AccountType.java
  src/main/java/com/community/infra/aws/S3Service.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/profile/settings/profile-img.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix

#350 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/account/Account.java
  src/main/java/com/community/domain/account/AccountType.java
  src/main/java/com/community/infra/aws/S3Service.java
  src/main/java/com/community/service/AccountService.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/profile/settings/profile-img.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#351 theme-frag 대메뉴 및 내용 수정
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#352 branch up-to-date
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#354 Bookmark 추가(Board, Council, Market) / Theme-Fragments Ajax 추가
  src/main/java/com/community/domain/bookmark/Bookmark.java
  src/main/java/com/community/domain/bookmark/BookmarkRepository.java
  src/main/java/com/community/service/BookmarkService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/BookmarkController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#355 branch up-to-date
  src/main/java/com/community/domain/bookmark/Bookmark.java
  src/main/java/com/community/domain/bookmark/BookmarkRepository.java
  src/main/java/com/community/service/BookmarkService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/BookmarkController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#356 market enum 타입 변경 / 로직 추가 수정
  src/main/java/com/community/domain/market/MarketItemStatus.java
  src/main/java/com/community/domain/study/StudyRepository.java
  src/main/java/com/community/domain/study/StudyRepositoryExtension.java
  src/main/java/com/community/domain/study/StudyRepositoryExtensionImpl.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/profile/view.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#358 branch up-to-date
  src/main/java/com/community/domain/market/MarketItemStatus.java
  src/main/java/com/community/domain/study/StudyRepository.java
  src/main/java/com/community/domain/study/StudyRepositoryExtension.java
  src/main/java/com/community/domain/study/StudyRepositoryExtensionImpl.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/profile/view.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#357 Bookmark View 수정 / Entity별 BookmarkList 추가
  src/main/java/com/community/domain/board/Board.java
  src/main/java/com/community/domain/council/Council.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/bookmark/bookmarks.html
Labels: enhancement

#359 branch up-to-date
  src/main/java/com/community/domain/board/Board.java
  src/main/java/com/community/domain/council/Council.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/bookmark/bookmarks.html
Labels: branch up-to-date

#360 study 북마크 / market 검색 / graduation (졸작) 추가
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/market/MarketRepository.java
  src/main/java/com/community/domain/market/MarketRepositoryExtension.java
  src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
  src/main/java/com/community/domain/study/StudyRepository.java
  src/main/java/com/community/infra/config/SecurityConfig.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/market/market-search.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#361 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/domain/market/MarketRepository.java
  src/main/java/com/community/domain/market/MarketRepositoryExtension.java
  src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
  src/main/java/com/community/domain/study/StudyRepository.java
  src/main/java/com/community/infra/config/SecurityConfig.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/market/market-search.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#362 Council Like 추가 / Board View 버그 수정 / Reply Ajax Fragments로 이동 / 북마크 페이지 수정 진행중
  src/main/java/com/community/domain/council/Council.java
  src/main/java/com/community/domain/likes/LikeRepository.java
  src/main/java/com/community/domain/likes/Likes.java
  src/main/java/com/community/domain/market/Market.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/service/LikeService.java
  src/main/java/com/community/service/ReplyService.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/LikeApiController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix

#363 branch up-to-date
  src/main/java/com/community/domain/council/Council.java
  src/main/java/com/community/domain/likes/LikeRepository.java
  src/main/java/com/community/domain/likes/Likes.java
  src/main/java/com/community/domain/market/Market.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/service/LikeService.java
  src/main/java/com/community/service/ReplyService.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/LikeApiController.java
  src/main/java/com/community/web/controller/ReplyController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#364 졸작 MVC 추가 중 / 마켓 해결
  src/main/java/com/community/domain/graduation/Graduation.java
  src/main/java/com/community/domain/graduation/GraduationRepository.java
  src/main/java/com/community/service/GraduationService.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/GraduationController.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/dto/GraduationForm.java
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/graduation/graduation-form.html
  src/main/resources/templates/graduation/graduation-list.html
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#365 branch up-to-date
  src/main/java/com/community/domain/graduation/Graduation.java
  src/main/java/com/community/domain/graduation/GraduationRepository.java
  src/main/java/com/community/service/GraduationService.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/GraduationController.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/dto/GraduationForm.java
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/graduation/graduation-form.html
  src/main/resources/templates/graduation/graduation-list.html
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#366 마진 수정
  src/main/resources/static/images/default-image.png
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#367 Council, Board 페이지 내 검색 추가
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/domain/chat/ChatRepository.java
  src/main/java/com/community/domain/council/CouncilRepository.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/resources/templates/board/board-search.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/council-search.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#368 branch up-to-date
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/domain/chat/ChatRepository.java
  src/main/java/com/community/domain/council/CouncilRepository.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/ChatController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/resources/templates/board/board-search.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/council-search.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#369 졸작 이미지 다중 이미지 성공(업로드/삭제) / 자잘한 수정 내역들
  build.gradle
  src/main/java/com/community/domain/graduation/Graduation.java
  src/main/java/com/community/infra/aws/S3.java
  src/main/java/com/community/infra/aws/S3Service.java
  src/main/java/com/community/service/GraduationService.java
  src/main/java/com/community/web/controller/GraduationController.java
  src/main/resources/static/assets/js/custom.js
  src/main/resources/templates/alarm/view.html
  src/main/resources/templates/graduation/graduation-form.html
  src/main/resources/templates/graduation/graduation-list.html
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/study/study-list.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#370 S3Repository 추가
  src/main/java/com/community/infra/aws/S3Repository.java
Labels: enhancement

#371 졸업작품 이미지 수정 / update / delete
  src/main/java/com/community/infra/aws/S3.java
  src/main/java/com/community/infra/aws/S3Repository.java
  src/main/java/com/community/service/GraduationService.java
  src/main/java/com/community/web/controller/GraduationController.java
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/graduation/graduation-form.html
  src/main/resources/templates/graduation/graduation-list.html
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#372 branch up-to-date
  src/main/java/com/community/domain/graduation/Graduation.java
  src/main/resources/application.properties
  src/main/resources/templates/graduation/graduation-form.html
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#375 멤버 공백으로 인한 버그 해결
  src/main/resources/templates/graduation/graduation-list.html
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/theme-fragments.html
Labels: bug, enhancement, bug fix

#376 branch up-to-date
  src/main/resources/templates/graduation/graduation-list.html
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#377 장터 및 리드미 조금 수정
  README.md
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/MarketController.java
Labels: enhancement

#378 branch up-to-date
  README.md
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/MarketController.java
Labels: branch up-to-date

#379 Board, Council 이미지 업로드, 삭제, 수정 추가
  src/main/java/com/community/domain/board/Board.java
  src/main/java/com/community/domain/council/Council.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/service/CouncilService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/static/images/46.jpeg
  src/main/resources/static/images/59.jpeg
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/info/info-contact.html
  src/main/resources/templates/info/info-faq.html
  src/main/resources/templates/info/info-privacy.html
  src/main/resources/templates/theme-fragments.html
Labels: bug, enhancement

#380 branch up-to-date
  src/main/java/com/community/domain/board/Board.java
  src/main/java/com/community/domain/council/Council.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/service/CouncilService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/static/images/46.jpeg
  src/main/resources/static/images/59.jpeg
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-about.html
  src/main/resources/templates/info/info-contact.html
  src/main/resources/templates/info/info-faq.html
  src/main/resources/templates/info/info-privacy.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#381 마켓 업로드 / 삭제 구현
  src/main/java/com/community/domain/market/Market.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/dto/GraduationForm.java
  src/main/java/com/community/web/dto/MarketForm.java
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#382 branch up-to-date
  src/main/java/com/community/domain/market/Market.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/dto/GraduationForm.java
  src/main/java/com/community/web/dto/MarketForm.java
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#383 npm 추가 설치 / 여러 페이지 뷰 조정 / Inquire(건의사항) Entity 생성
  src/main/java/com/community/domain/inquire/Inquire.java
  src/main/java/com/community/domain/inquire/InquireRepository.java
  src/main/java/com/community/infra/aws/S3.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/service/InfoPageService.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-contact-detail.html
  src/main/resources/templates/info/info-contact.html
  src/main/resources/templates/info/info-faq.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#384 branch up-to-date
  src/main/java/com/community/domain/inquire/Inquire.java
  src/main/java/com/community/domain/inquire/InquireRepository.java
  src/main/java/com/community/infra/aws/S3.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/service/InfoPageService.java
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/info/info-contact-detail.html
  src/main/resources/templates/info/info-contact.html
  src/main/resources/templates/info/info-faq.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#385 InfoPage 수정
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/info/info-contact.html
Labels: enhancement

#387 branch up-to-date
  src/main/java/com/community/web/controller/InfoPageController.java
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/info/info-contact.html
Labels: branch up-to-date

#388 Manager 페이지 수정 / Info 페이지 조정
  src/main/java/com/community/manager/ManagerController.java
  src/main/resources/templates/info/info-faq.html
  src/main/resources/templates/manager-fragments.html
  src/main/resources/templates/manager/m_account.html
  src/main/resources/templates/manager/tables.html
Labels: enhancement

#389 branch up-to-date
  src/main/java/com/community/manager/ManagerController.java
  src/main/resources/templates/info/info-faq.html
  src/main/resources/templates/manager-fragments.html
  src/main/resources/templates/manager/m_account.html
  src/main/resources/templates/manager/tables.html
Labels: branch up-to-date

#386 멀티이미지 각각의 delete 성공 / 마켓 및 프로필 버그 해결
  src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
  src/main/java/com/community/infra/aws/S3Controller.java
  src/main/java/com/community/infra/aws/S3Service.java
  src/main/java/com/community/service/GraduationService.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/GraduationController.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/profile/view.html
  src/main/resources/templates/theme-fragments.html
Labels: bug, enhancement, bug fix

#390 branch up-to-date
  src/main/java/com/community/domain/market/MarketRepositoryExtensionImpl.java
  src/main/java/com/community/infra/aws/S3Controller.java
  src/main/java/com/community/infra/aws/S3Service.java
  src/main/java/com/community/service/GraduationService.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/GraduationController.java
  src/main/java/com/community/web/controller/MarketController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/market/market-list.html
  src/main/resources/templates/profile/view.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#391 board, council image delete 수정
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/council/council-detail.html
Labels: enhancement

#392 branch up-to-date
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#393 Board, Council Controller, Service 수정
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/service/CouncilService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/CouncilController.java
Labels: enhancement

#394 이미지 업로드 require 수정
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/CouncilController.java
Labels: enhancement

#395 board 뒤로가기 추가 / board 소제목 <-> 서브분류 버그 해결
  src/main/java/com/community/domain/board/Board.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/index.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix

#396 branch up-to-date
  src/main/java/com/community/infra/alarm/ReplyEventListener.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/GraduationController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/java/com/community/web/dto/AccountForm.java
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/graduation/graduation-form.html
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/profile/settings/account.html
  src/main/resources/templates/profile/settings/alarm.html
  src/main/resources/templates/profile/settings/password.html
  src/main/resources/templates/profile/settings/profile-settings.html
  src/main/resources/templates/profile/settings/tags.html
  src/main/resources/templates/profile/settings/withdraw.html
  src/main/resources/templates/study/study-meetings.html
Labels: branch up-to-date

#397 branch up-to-date
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/info/info-faq.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#398 branch up-to-date
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/bookmark/bookmarks.html
Labels: branch up-to-date

#399 branch up-to-date
  src/main/resources/templates/bookmark/bookmarks.html
Labels: branch up-to-date

#400 profile byAccount 수정
  src/main/java/com/community/web/controller/ProfileController.java
Labels: enhancement

#402 스터디 날짜 버그 해결
  src/main/java/com/community/domain/board/Board.java
  src/main/java/com/community/domain/study/Study.java
  src/main/java/com/community/domain/study/StudyRepositoryExtensionImpl.java
  src/main/java/com/community/infra/alarm/ReplyEventListener.java
  src/main/java/com/community/service/BoardService.java
  src/main/java/com/community/service/CouncilService.java
  src/main/java/com/community/service/MarketService.java
  src/main/java/com/community/service/StudyService.java
  src/main/java/com/community/web/controller/AlarmController.java
  src/main/java/com/community/web/controller/BaseController.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/java/com/community/web/controller/GraduationController.java
  src/main/java/com/community/web/controller/MainController.java
  src/main/java/com/community/web/controller/ProfileController.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/java/com/community/web/dto/AccountForm.java
  src/main/java/com/community/web/dto/StudyCalendarForm.java
  src/main/java/com/community/web/dto/StudyForm.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/boards.html
  src/main/resources/templates/bookmark/bookmarks.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/graduation/graduation-form.html
  src/main/resources/templates/graduation/graduation-view.html
  src/main/resources/templates/index.html
  src/main/resources/templates/info/info-faq.html
  src/main/resources/templates/market/market-detail.html
  src/main/resources/templates/market/market-form.html
  src/main/resources/templates/profile/settings/account.html
  src/main/resources/templates/profile/settings/alarm.html
  src/main/resources/templates/profile/settings/password.html
  src/main/resources/templates/profile/settings/profile-settings.html
  src/main/resources/templates/profile/settings/tags.html
  src/main/resources/templates/profile/settings/withdraw.html
  src/main/resources/templates/study/settings/calendar.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-meetings.html
  src/main/resources/templates/study/study-view.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#403 branch up-to-date
  src/main/java/com/community/service/StudyService.java
  src/main/java/com/community/web/controller/StudyController.java
  src/main/java/com/community/web/dto/StudyCalendarForm.java
  src/main/java/com/community/web/dto/StudyForm.java
  src/main/resources/templates/study/settings/calendar.html
  src/main/resources/templates/study/study-form.html
  src/main/resources/templates/study/study-view.html
Labels: branch up-to-date

#404 Council LocalDateTime 변경
  src/main/java/com/community/domain/council/Council.java
  src/main/java/com/community/service/CouncilService.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
Labels: enhancement

#405 board-detail 이미지 사이즈 조정
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement

#406 branch up-to-date
  src/main/java/com/community/domain/council/Council.java
  src/main/java/com/community/service/CouncilService.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/resources/templates/account/email-login-view.html
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/councils.html
  src/main/resources/templates/theme-fragments.html
Labels: branch up-to-date

#407 Board, Council 검색 쿼리 수정 / Council Search View 수정 + 이미지 없을 때 수정
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/domain/council/CouncilRepository.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/java/com/community/web/controller/CouncilController.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/council/council-detail.html
  src/main/resources/templates/council/council-search.html
  src/main/resources/templates/council/councils.html
Labels: enhancement

#410 branch up-to-date
  src/main/java/com/community/web/controller/StudyController.java
  src/main/resources/templates/account/email-login-view.html
Labels: branch up-to-date

#409 Board Search JPA -> QueryDsl로 변경
  src/main/java/com/community/domain/board/BoardRepository.java
  src/main/java/com/community/domain/board/BoardRepositoryExtension.java
  src/main/java/com/community/domain/board/BoardRepositoryExtensionImpl.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/resources/templates/manager-fragments.html
Labels: enhancement

#411 Board Search 버그 수정
  src/main/java/com/community/domain/board/BoardRepositoryExtensionImpl.java
  src/main/java/com/community/web/controller/BoardController.java
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/board/board-search.html
  src/main/resources/templates/info/info-faq.html
  src/main/resources/templates/manager-fragments.html
  src/main/resources/templates/theme-fragments.html
Labels: enhancement, bug fix
