Repository lee-ji-hoon/community, pull requests merged in 2022-02, with the labels that each got.

#65 스터디 설정 변경) 배너, 태그 추가 삭제
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyRepository.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/tag/Tag.java
  src/main/java/com/community/tag/TagForm.java
  src/main/java/com/community/tag/TagRepository.java
  src/main/java/com/community/tag/TagService.java
  src/main/java/com/community/zone/Zone.java
  src/main/java/com/community/zone/ZoneForm.java
  src/main/java/com/community/zone/ZoneRepository.java
  src/main/java/com/community/zone/ZoneService.java
  src/main/resources/templates/fragments.html
  src/main/resources/templates/settings/tags.html
  src/main/resources/templates/study/settings/banner.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/tags.html
Labels: enhancement

#68 branch up-to-date
  src/main/java/com/community/account/entity/Account.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyRepository.java
  src/main/java/com/community/study/StudyService.java
  src/main/java/com/community/tag/Tag.java
  src/main/java/com/community/tag/TagForm.java
  src/main/java/com/community/tag/TagRepository.java
  src/main/java/com/community/tag/TagService.java
  src/main/java/com/community/zone/Zone.java
  src/main/java/com/community/zone/ZoneForm.java
  src/main/java/com/community/zone/ZoneRepository.java
  src/main/java/com/community/zone/ZoneService.java
  src/main/resources/templates/fragments.html
  src/main/resources/templates/settings/tags.html
  src/main/resources/templates/study/settings/banner.html
  src/main/resources/templates/study/settings/description.html
  src/main/resources/templates/study/settings/tags.html
Labels: branch up-to-date

#70 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/BoardController.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/like/LikeService.java
  src/main/java/com/community/profile/service/ProfileService.java
Labels: branch up-to-date

#71 게시글 삭제 bug fix / 이미지 및 members.html 추가
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/entity/Board.java
  src/main/resources/static/images/multimedia.png
  src/main/resources/static/images/study-banner.jpeg
  src/main/resources/templates/study/members.html
Labels: bug, enhancement, bug fix

#72 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/entity/Board.java
  src/main/resources/static/images/multimedia.png
  src/main/resources/static/images/study-banner.jpeg
  src/main/resources/templates/study/members.html
Labels: branch up-to-date

#73 댓글 수정 및 삭제 구현
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/BoardController.java
  src/main/java/com/community/board/entity/Board.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/form/ReplyForm.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/java/com/community/like/LikeApiController.java
  src/main/java/com/community/like/LikeRepository.java
  src/main/java/com/community/like/LikeService.java
  src/main/java/com/community/like/Likes.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/student-council22.html
Labels: enhancement

#75 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/BoardController.java
  src/main/java/com/community/board/entity/Board.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/form/ReplyForm.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/repository/ReplyRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/java/com/community/like/LikeApiController.java
  src/main/java/com/community/like/LikeRepository.java
  src/main/java/com/community/like/LikeService.java
  src/main/java/com/community/like/Likes.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/student-council22.html
Labels: branch up-to-date

#74 스터디 설정 및 추가
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/account/AccountService.java
  src/main/java/com/community/account/repository/AccountRepository.java
  src/main/java/com/community/account/repository/PersistentLoginsRepository.java
  src/main/java/com/community/account/validator/SignUpFormValidator.java
  src/main/java/com/community/board/BoardController.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/java/com/community/profile/validator/NicknameValidator.java
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyRepository.java
  src/main/java/com/community/study/StudyService.java
  src/main/resources/templates/fragments.html
  src/main/resources/templates/settings/tags.html
  src/main/resources/templates/settings/zones.html
  src/main/resources/templates/study/settings/study.html
  src/main/resources/templates/study/settings/zones.html
  src/main/resources/templates/study/study-list.html
  src/test/java/com/community/account/AccountControllerTest.java
  src/test/java/com/community/account/MainControllerTest.java
Labels: enhancement

#76 branch up-to-date
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/account/AccountService.java
  src/main/java/com/community/account/repository/AccountRepository.java
  src/main/java/com/community/account/repository/PersistentLoginsRepository.java
  src/main/java/com/community/account/validator/SignUpFormValidator.java
  src/main/java/com/community/board/BoardController.java
  src/main/java/com/community/profile/ProfileController.java
  src/main/java/com/community/profile/service/ProfileService.java
  src/main/java/com/community/profile/validator/NicknameValidator.java
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/StudyRepository.java
  src/main/java/com/community/study/StudyService.java
  src/main/resources/templates/fragments.html
  src/main/resources/templates/settings/tags.html
  src/main/resources/templates/settings/zones.html
  src/main/resources/templates/study/settings/study.html
  src/main/resources/templates/study/settings/zones.html
  src/main/resources/templates/study/study-list.html
  src/test/java/com/community/account/AccountControllerTest.java
  src/test/java/com/community/account/MainControllerTest.java
Labels: branch up-to-date

#79 게시판 폴더 및 코드 리팩터링
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/entity/Board.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/repository/ReportRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/java/com/community/board/service/ReportService.java
  src/main/java/com/community/config/SecurityConfig.java
  src/main/java/com/community/like/LikeRepository.java
  src/main/java/com/community/report/ReportController.java
  src/main/java/com/community/report/entity/BoardReport.java
  src/main/java/com/community/report/entity/ReplyReport.java
  src/main/java/com/community/report/form/BoardReportForm.java
  src/main/java/com/community/report/form/ReplyReportForm.java
  src/main/java/com/community/report/repository/BoardReportRepository.java
  src/main/java/com/community/report/repository/ReplyReportRepository.java
  src/main/java/com/community/report/service/ReportService.java
  src/main/resources/templates/board/board-list.html
  src/main/resources/templates/board/board-main.html
  src/main/resources/templates/board/detail-fragments.html
  src/main/resources/templates/board/detail.html
Labels: enhancement, bug fix

#80 버그 픽스 확인
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/controller/ReplyController.java
  src/main/java/com/community/board/entity/Board.java
  src/main/java/com/community/board/entity/Reply.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/board/repository/ReportRepository.java
  src/main/java/com/community/board/service/BoardService.java
  src/main/java/com/community/board/service/ReplyService.java
  src/main/java/com/community/board/service/ReportService.java
  src/main/java/com/community/config/SecurityConfig.java
  src/main/java/com/community/like/LikeRepository.java
  src/main/java/com/community/report/ReportController.java
  src/main/java/com/community/report/entity/BoardReport.java
  src/main/java/com/community/report/entity/ReplyReport.java
  src/main/java/com/community/report/form/BoardReportForm.java
  src/main/java/com/community/report/form/ReplyReportForm.java
  src/main/java/com/community/report/repository/BoardReportRepository.java
  src/main/java/com/community/report/repository/ReplyReportRepository.java
  src/main/java/com/community/report/service/ReportService.java
  src/main/resources/templates/board/board-list.html
  src/main/resources/templates/board/board-main.html
  src/main/resources/templates/board/detail-fragments.html
  src/main/resources/templates/board/detail.html
Labels: branch up-to-date

#81 프로필 뷰 전체적인 수정
  README.md
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/account/repository/AccountRepository.java
  src/main/java/com/community/like/LikeRepository.java
  src/main/java/com/community/study/StudyRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/meeting/form.html
  src/main/resources/templates/settings/zones.html
Labels: enhancement

#82 branch up-to-date
  README.md
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/account/repository/AccountRepository.java
  src/main/java/com/community/like/LikeRepository.java
  src/main/java/com/community/study/StudyRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/meeting/form.html
  src/main/resources/templates/settings/zones.html
Labels: branch up-to-date

#83 study view 추가 중
  src/main/resources/templates/fragments.html
  src/main/resources/templates/meeting/form.html
  src/main/resources/templates/study/form.html
  src/main/resources/templates/study/settings/banner.html
  src/main/resources/templates/study/view.html
Labels: enhancement

#85 branch up-to-date
  src/main/resources/templates/fragments.html
  src/main/resources/templates/meeting/form.html
  src/main/resources/templates/study/form.html
  src/main/resources/templates/study/settings/banner.html
  src/main/resources/templates/study/view.html
Labels: branch up-to-date

#84 Profile -> Board 추가
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/form/BoardForm.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/config/SecurityConfig.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/board/board-list.html
  src/main/resources/templates/board/board-write.html
Labels: enhancement, bug fix

#86 게시판 버그 해결 확인
  src/main/java/com/community/TestDataInit.java
  src/main/java/com/community/account/AccountController.java
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/board/form/BoardForm.java
  src/main/java/com/community/board/repository/BoardRepository.java
  src/main/java/com/community/config/SecurityConfig.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/board/board-list.html
  src/main/resources/templates/board/board-write.html
Labels: branch up-to-date

#87 스터디 날짜 추가
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/form/StudyForm.java
  src/main/java/com/community/study/validator/StudyFormValidator.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/study/form.html
  src/main/resources/templates/study/view.html
Labels: enhancement

#88 branch up-to-date
  src/main/java/com/community/study/Study.java
  src/main/java/com/community/study/StudyController.java
  src/main/java/com/community/study/form/StudyForm.java
  src/main/java/com/community/study/validator/StudyFormValidator.java
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/study/form.html
  src/main/resources/templates/study/view.html
Labels: branch up-to-date

#90 좋아요 ajax 기능 추가
  build.gradle
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/like/LikeApiController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/board/board-list.html
  src/main/resources/templates/board/detail-fragments.html
  src/main/resources/templates/board/detail.html
Labels: bug, enhancement

#91 좋아요 기능 확인
  build.gradle
  src/main/java/com/community/board/controller/BoardController.java
  src/main/java/com/community/like/LikeApiController.java
  src/main/resources/application-dev.properties
  src/main/resources/templates/board/board-list.html
  src/main/resources/templates/board/detail-fragments.html
  src/main/resources/templates/board/detail.html
Labels: branch up-to-date
